# Generated by Django 4.2.2 on 2023-06-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_menuitem_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='bookingdate',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='num_guests',
            new_name='no_of_guests',
        ),
    ]
